### ISSUE TITLE
Setting up database infinite "Please Wait..."

### ISSUE THREAD

**Issue by hjone72** [LinxHQ/linxbooks#14]
When setting up the DB for the first time, after clicking save, a message box appears that says "Please wait.." this never goes away.
![image](https://cloud.githubusercontent.com/assets/4342811/15109390/89e8dc58-161e-11e6-8bbf-f3b3afac4395.png)

**Comment by josephpnc** [comment]
@nhuhtlb @HoDucTien37

**Comment by sibidharan** [comment]
It is due to the file permission error. Check the Network tab of the Web Inspector, and check the response. It will say a write permission deny to some db.php file. 

As a quick fix, I set 777 to all the files and folders while setting up and then changed back to 755 for folders and 640 for files lately. Yet, some catch and upload folders require write permissions.

**Comment by josephpnc** [comment]
Thanks. Our documentation definitely needs some update about that.

Sent from my Samsung device

-------- Original message --------

**Comment by josephpnc** [comment]
@mrtran151190 for follow up

**Comment by linxbooksadmin** [comment]
I've uploaded latest ver to github. Please read the README for installation instruction. the current web install interface is not updated yet.
